name: Cache CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      #   - name: Install CMake
      #     uses: jwlawson/actions-setup-cmake@v1.14
      #     with:
      #       cmake-version: "3.22.x"

      - name: Install dependences
        run: |
          sudo apt update
          sudo apt install -y cmake build-essential libgtest-dev

      - name: Build
        run: |
          cmake -S ./ -B ./build
          cmake --build ./build

      - name: LFU tests
        run: |
          ./build/lfu_tests
          ./build/pc_tests

      - name: Show date
        run: date
