name: Cache CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependences
        run: echo "Installing dependences..."
          sudo apt-get install cmake
          sudo apt-get install libgtest-dev

      - name: Build
        run: echo "Building project..."
          cmake -S ./ -B ./build
          cmake --build ./build

      - name: Show date
        run: date
